pipelines:
  default:
    - step:
        name: 'Deploy Todo App'
        runs-on:
          - 'self.hosted'
          - 'linux.shell'  # Updated to match the runner's label
        script:
          # Stop existing containers
          - docker compose down || true

          - export DOCKER_HOST=unix:///var/run/docker.sock
          
          # Build and start all services
          - docker compose up -d --build
          
          # Wait for services with a longer timeout
          - sleep 30  # Increased from 20 to give more time for startup
          
          # Health check with retry
          - |
            for i in {1..5}; do
              if curl -f http://localhost:5000/api/health; then
                echo "Health check passed"
                break
              else
                echo "Health check failed, retrying... ($i/5)"
                sleep 5
              fi
            done
          
          - echo "Todo App deployed successfully"
