image: node:18

pipelines:
  default:
    - step:
        name: 'Build and Test'
        script:
          - echo "Setting up the app..."
          - npm install
          - echo "Checking if the app works..."
          - npm test
        caches:
          - node
    - step:
        name: 'Deploy to Production'
        deployment: production
        trigger: 'manual'
        script:
          - echo "Copying files to production..."
          - apt-get update && apt-get install -y rsync
          - rsync -rav --delete ./ ubuntu@103.90.86.229:/var/www/app/
          - echo "Starting the app on production..."
          - ssh -p 8080 ubuntu@103.90.86.229 "cd /var/www/app && npm install --production && npm start"
